# Generated by Django 3.2.16 on 2022-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_info', models.CharField(max_length=200, verbose_name='Tool Info')),
                ('insert', models.CharField(max_length=200, verbose_name='Insert')),
                ('machine', models.CharField(max_length=200, verbose_name='Machines')),
                ('estimated_hours', models.IntegerField(verbose_name='Estimated Hours')),
                ('date', models.DateField(verbose_name='Insertion Date')),
            ],
        ),
    ]
