# Generated by Django 3.2.16 on 2022-11-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMachineHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_info', models.CharField(blank=True, max_length=200, verbose_name='Tool Info')),
                ('insert', models.CharField(blank=True, max_length=200, verbose_name='Insert')),
                ('machine', models.CharField(blank=True, max_length=200, verbose_name='Machines')),
                ('daily_hours', models.IntegerField(blank=True, null=True, verbose_name='Actual Machine Hours')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Insertion Date')),
                ('comments', models.TextField(blank=True, help_text='text', null=True, verbose_name='Comments')),
            ],
        ),
        migrations.AlterField(
            model_name='estimatedhours',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Insertion Date'),
        ),
        migrations.AlterField(
            model_name='estimatedhours',
            name='estimated_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.AlterField(
            model_name='estimatedhours',
            name='insert',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Insert'),
        ),
        migrations.AlterField(
            model_name='estimatedhours',
            name='machine',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Machines'),
        ),
        migrations.AlterField(
            model_name='estimatedhours',
            name='tool_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tool Info'),
        ),
    ]
