# Generated by Django 3.2.16 on 2022-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_dailymachinehoursinput_qualityreportinput_totalloadonsystemsinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='machine_insert_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Machine Insert Name'),
        ),
    ]
