# Generated by Django 3.2.16 on 2022-11-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_dailymachinehoursinput_machine_insert_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailymachinehoursinput',
            table='DailyMachineHoursInput',
        ),
        migrations.AlterModelTable(
            name='qualityreportinput',
            table='QualityReportInput',
        ),
        migrations.AlterModelTable(
            name='totalloadonsystemsinput',
            table='TotalLoadOnSystemsInput',
        ),
    ]
