# Generated by Django 3.2.16 on 2022-12-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20221130_0709'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailymachinehours',
            table='Daily_Machine_Hours',
        ),
    ]
