# Generated by Django 3.2.16 on 2022-12-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_dailymachinehours_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymachinehoursinput',
            old_name='machine_insert_name',
            new_name='machine_name',
        ),
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='department',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='totalloadonsystemsinput',
            name='department',
        ),
        migrations.RemoveField(
            model_name='totalloadonsystemsinput',
            name='machines',
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='machine'),
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='machine'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='totalloadonsystemsinput',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='machine'),
        ),
        migrations.AddField(
            model_name='totalloadonsystemsinput',
            name='unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='dailymachinehours',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='machines'),
        ),
        migrations.AlterField(
            model_name='estimatedhours',
            name='machine',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='machine'),
        ),
    ]
