# Generated by Django 3.2.16 on 2022-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20221219_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='machine',
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='edm',
            field=models.CharField(blank=True, max_length=200, verbose_name='EDM'),
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='milling',
            field=models.CharField(blank=True, max_length=200, verbose_name='Milling'),
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='turning',
            field=models.CharField(blank=True, max_length=200, verbose_name='Turning'),
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='wire_cut',
            field=models.CharField(blank=True, max_length=200, verbose_name='Wire Cut'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='edm',
            field=models.CharField(blank=True, max_length=200, verbose_name='EDM'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='milling',
            field=models.CharField(blank=True, max_length=200, verbose_name='Milling'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='turning',
            field=models.CharField(blank=True, max_length=200, verbose_name='Turning'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='wire_cut',
            field=models.CharField(blank=True, max_length=200, verbose_name='Wire Cut'),
        ),
        migrations.AlterField(
            model_name='totalloadonsystemsinput',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='Machine'),
        ),
    ]
