# Generated by Django 3.2.16 on 2022-12-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20221219_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='edm',
        ),
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='milling',
        ),
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='turning',
        ),
        migrations.RemoveField(
            model_name='dailymachinehoursinput',
            name='wire_cut',
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='Machine'),
        ),
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='machine_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Machine Name'),
        ),
    ]
