# Generated by Django 3.2.16 on 2022-12-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20221219_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreportinput',
            name='insert',
            field=models.CharField(blank=True, max_length=200, verbose_name='Insert'),
        ),
    ]
