# Generated by Django 3.2.16 on 2023-01-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_totalloadonsystemsinput_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='totalloadonsystemsinput',
            unique_together=set(),
        ),
    ]
