# Generated by Django 3.2.16 on 2023-01-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_remove_totalloadonsystemsinput_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymachinehoursinput',
            name='status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Status'),
        ),
    ]
