# Generated by Django 3.2.16 on 2023-01-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_dailymachinehoursinput_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='edm',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='milling',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='turning',
        ),
        migrations.RemoveField(
            model_name='qualityreportinput',
            name='wire_cut',
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='deviation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deviation'),
        ),
        migrations.AddField(
            model_name='qualityreportinput',
            name='machine',
            field=models.CharField(blank=True, max_length=200, verbose_name='Machine'),
        ),
    ]
